DROP DATABASE IF EXISTS DB_TCCGRUPO5;
CREATE DATABASE DB_TCCGRUPO5;

USE DB_TCCGRUPO5;

CREATE TABLE USUARIO (
	IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(100)
	, EMAIL VARCHAR(100)
	, SENHA VARCHAR(45)
)ENGINE INNODB;

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100),
	EMAIL VARCHAR(100),
	CPF CHAR(11),
	TELEFONE_CONTATO VARCHAR(15),
	RUA VARCHAR(100),
	NUMERO INT,
	BAIRRO VARCHAR(100),
	CIDADE VARCHAR(100),
	ESTADO CHAR(2),
	CEP CHAR(8)
)ENGINE INNODB;

CREATE TABLE ORCAMENTO (
	IDORCAMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, IDUSUARIO INT NOT NULL
	, IDCLIENTE INT NOT NULL
	, PRAZO INT
	, DT_ORCAMENTO DATE
	, VALIDADE INT
	, IMPOSTO NUMERIC(8,2)
	, CONSTRAINT FK_ORCAMENTO_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO) ON UPDATE CASCADE ON DELETE CASCADE
	, CONSTRAINT FK_ORCAMENTO_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE INNODB;

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(255),
	VALOR_UNITARIO NUMERIC(8,2)
)ENGINE INNODB;

CREATE TABLE ITEM (
	IDITEM INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, IDORCAMENTO INT NOT NULL
	, TITULO VARCHAR(100)
	, DESCRICAO TEXT
	, VALOR NUMERIC(8,2)
	, CONSTRAINT FK_ITEM_ORCAMENTO FOREIGN KEY (IDORCAMENTO) REFERENCES ORCAMENTO (IDORCAMENTO) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE INNODB;

CREATE TABLE UTILIZAR (
	IDITEM INT NOT NULL
	, IDPRODUTO INT NOT NULL
	, QTDE INT
	, VALOR_UNITARIO NUMERIC(8,2)
	, CONSTRAINT PK_UTILIZAR PRIMARY KEY (IDITEM, IDPRODUTO)
	, CONSTRAINT FK_UTILIZAR_ITEM FOREIGN KEY (IDITEM) REFERENCES ITEM (IDITEM) ON UPDATE CASCADE ON DELETE CASCADE
	, CONSTRAINT FK_UTILIZAR_PRODUTO FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE INNODB;

